### like article
POST localhost:8080/api/v1/article_like/like/93a46013-8e44-4fd6-bade-7027269842df
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzcxMjc4NCwiZXhwIjoxNzYzNzk5MTg0fQ.kRQ95iacJZ3u2an4wW9jBP-9mR0xJnk3nVcfy80Llhpdfzt7M-A2GtE26JyL-82yzee2Lt5s0zczSnLDmSe_oA

### dislike article
POST localhost:8080/api/v1/article_like/dislike/93a46013-8e44-4fd6-bade-7027269842df
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfUFVCTElTSCJdLCJzdWIiOiJmYWxzZSIsImlhdCI6MTc2MzU0MjEzOCwiZXhwIjoxNzYzNjI4NTM4fQ.PjapKJz8QeTZpezWDasyodtd8HIR2vNiYXVVjZ65dSQKkX3wZthFpUs1JuJ9EV7SVhIHyA6rfrOj72xboMkmQw

### remove like
DELETE localhost:8080/api/v1/article_like/delete/93a46013-8e44-4fd6-bade-7027269842df
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfUFVCTElTSCJdLCJzdWIiOiJmYWxzZSIsImlhdCI6MTc2MzU0MjEzOCwiZXhwIjoxNzYzNjI4NTM4fQ.PjapKJz8QeTZpezWDasyodtd8HIR2vNiYXVVjZ65dSQKkX3wZthFpUs1JuJ9EV7SVhIHyA6rfrOj72xboMkmQw