### Create article
POST localhost:8080/api/v1/article
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzA1MTU5MywiZXhwIjoxNzYzMTM3OTkzfQ.EepbcIwAJSCO8T8EpB8J3V2jUJkNiPUA88jTnbFU8LT_BMqHeig0bM7K9QDa1YD3gqYP5CNllnkAd7C4UDX16w

{
  "title": "aaa5",
  "content": "aaaa5",
  "description": "aaaa5",
  "imageId": "1",
  "readTime": 4,
  "regionId": 2,
  "categoryList": [
    {
      "id": 1
    }
  ],
  "sectionList": [
    {
      "id": 2
    },
    {
      "id": 1
    }
  ],
  "tagList": [
    {
      "id": 4
    },
    {
      "id": 5
    }
  ]
}

### Update article
PUT localhost:8080/api/v1/article/3fa7ba88-fad8-4a73-a2fc-d1b1678c7b9e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzA1MTU5MywiZXhwIjoxNzYzMTM3OTkzfQ.EepbcIwAJSCO8T8EpB8J3V2jUJkNiPUA88jTnbFU8LT_BMqHeig0bM7K9QDa1YD3gqYP5CNllnkAd7C4UDX16w

{
  "title": "gh",
  "content": "ihjkml",
  "description": "uhnjmk",
  "readTime": 4,
  "regionId": 1,
  "categoryList": [
    {
      "id": 1
    }
  ],
  "sectionList": [
    {
      "id": 1
    }
  ]
}

### Delete article
DELETE localhost:8080/api/v1/article/3fa7ba88-fad8-4a73-a2fc-d1b1678c7b9e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzA1MTU5MywiZXhwIjoxNzYzMTM3OTkzfQ.EepbcIwAJSCO8T8EpB8J3V2jUJkNiPUA88jTnbFU8LT_BMqHeig0bM7K9QDa1YD3gqYP5CNllnkAd7C4UDX16w

### change status
PUT localhost:8080/api/v1/article/93a46013-8e44-4fd6-bade-7027269842df/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfUFVCTElTSCJdLCJzdWIiOiJmYWxzZSIsImlhdCI6MTc2MzExOTExNSwiZXhwIjoxNzYzMjA1NTE1fQ.USG3BohPpTiHmULMSg4sc33Y5jqvvHvtAIhIV0aRBdH_wTkfm-X0MhIRQeUbnuh1LdKToX-E_Pf7SeUtzSITqw

{
  "status": "PUBLISHED"
}

### get article By section Id
GET localhost:8080/api/v1/article/section/1

### get article By category Id
GET localhost:8080/api/v1/article/category/1

### get article By region Id
GET localhost:8080/api/v1/article/region/1

### get article Id
GET localhost:8080/api/v1/article/get/93a46013-8e44-4fd6-bade-7027269842df
Accept-Language: EN

### get last 12
POST localhost:8080/api/v1/article/last12
Content-Type: application/json

[
  "93a46013-8e44-4fd6-bade-7027269842df"
]

### get by section Id and except article Id
POST localhost:8080/api/v1/article/section/2/last4?exceptArticleId=3fa7ba88-fad8-4a73-a2fc-d1b1678c7b9e

### get View top 4 and except article Id
POST localhost:8080/api/v1/article/view_top4?exceptArticleId=3fa7ba88-fad8-4a73-a2fc-d1b1678c7b9e

### get View count By article Id
GET localhost:8080/api/v1/article/increase/view/3fa7ba88-fad8-4a73-a2fc-d1b1678c7b9e

### get Shared count By article Id
GET localhost:8080/api/v1/article/increase/shared/3fa7ba88-fad8-4a73-a2fc-d1b1678c7b9e

### get tagName
GET localhost:8080/api/v1/article/tagName/tag2?limit=7

### filter Any
POST localhost:8080/api/v1/article/user/filter
Content-Type: application/json

{
  "title": "aaa",
  "categoryId": 1,
  "sectionId": 2
}

### filter moderator
POST localhost:8080/api/v1/article/moderator/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzIzNjUyMSwiZXhwIjoxNzYzMzIyOTIxfQ.dq7n-eVQR7gNkMgJ4tQHcaWeZV70NNlx8s6Nc4cI8WJ_5GYz9slrBfP16Kw4dF8QgyPKsa9fRu93tJvAnFCvEw

{
  "title": "aaa",
  "categoryId": 1,
  "sectionId": 2
}

### filter Admin
POST localhost:8080/api/v1/article/admin/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjMyMzYzNTEsImV4cCI6MTc2MzMyMjc1MX0.gTI3Rc3TZYRLDxIk_F52CEu9uCUBd4qAK2k5qMFuVfmpWtAttlvklv0Rrlxb4QTf0pnODJN_bRTKmbWAWlHcug

{
  "title": "aaa",
  "categoryId": 1,
  "sectionId": 2,
  "status": "NOT_PUBLISHED"
}