### Registration using Phone
POST localhost:8080/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Erali",
  "surname": "MURODULLAYEV",
  "username": "+998930544807",
  "password": "12345"
}

### Registration using gmail
POST localhost:8080/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Adham",
  "surname": "MURODULLAYEV",
  "username": "adhamjonyaxshiboyev@gmail.com",
  "password": "12345"
}

### Registration using sms
PUT localhost:8080/api/v1/auth/registration/sms/verification
Content-Type: application/json

{
  "phoneNumber": "998904917705",
  "code": "54306"
}
###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "adhamjonyaxshiboyev@gmail.com",
  "password": "12345"
}
