### Registration using Phone
POST localhost:8080/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Afandi",
  "surname": "Toshmatov",
  "username": "998904917705",
  "password": "12345"
}


### Registration using sms
PUT localhost:8080/api/v1/auth/registration/sms/verification
Content-Type: application/json

{
  "phoneNumber": "998904917705",
  "code": "54306"
}