### Create category
POST localhost:8080/api/v1/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjI3NTYwNTksImV4cCI6MTc2Mjg0MjQ1OX0.-n8cqxeqH7OwUySxorqqBzg4s1-p3d9rwIty9h9AqH4aNZ4aueUELjP1t6qpwn60fwOvau4jcPSp3s7MBbNDHQ

{
  "orderNumber": 1,
  "nameUz": "Jahon1",
  "nameRu": "Jahon_ru1",
  "nameEn": "Jahon_en1",
  "categoryKey": "Jahon1s"
}

### Get all category
GET localhost:8080/api/v1/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjI3NTYwNTksImV4cCI6MTc2Mjg0MjQ1OX0.-n8cqxeqH7OwUySxorqqBzg4s1-p3d9rwIty9h9AqH4aNZ4aueUELjP1t6qpwn60fwOvau4jcPSp3s7MBbNDHQ

### Update category
PUT localhost:8080/api/v1/category/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjI3NTYwNTksImV4cCI6MTc2Mjg0MjQ1OX0.-n8cqxeqH7OwUySxorqqBzg4s1-p3d9rwIty9h9AqH4aNZ4aueUELjP1t6qpwn60fwOvau4jcPSp3s7MBbNDHQ

{
  "orderNumber": 1,
  "nameUz": "T 1",
  "nameRu": "Ташкент 1",
  "nameEn": "Tashkent 1",
  "categoryKey": "tashkent1"
}

### Delete category
DELETE localhost:8080/api/v1/category/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjI3NTYwNTksImV4cCI6MTc2Mjg0MjQ1OX0.-n8cqxeqH7OwUySxorqqBzg4s1-p3d9rwIty9h9AqH4aNZ4aueUELjP1t6qpwn60fwOvau4jcPSp3s7MBbNDHQ

### Get by lang
GET localhost:8080/api/v1/category/lang
Accept-Language: EN