### like commit
POST localhost:8080/api/v1/comment_like/like/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzcxMjc4NCwiZXhwIjoxNzYzNzk5MTg0fQ.kRQ95iacJZ3u2an4wW9jBP-9mR0xJnk3nVcfy80Llhpdfzt7M-A2GtE26JyL-82yzee2Lt5s0zczSnLDmSe_oA

### dislike commit
POST localhost:8080/api/v1/comment_like/dislike/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzcxMjc4NCwiZXhwIjoxNzYzNzk5MTg0fQ.kRQ95iacJZ3u2an4wW9jBP-9mR0xJnk3nVcfy80Llhpdfzt7M-A2GtE26JyL-82yzee2Lt5s0zczSnLDmSe_oA

### remove like
DELETE localhost:8080/api/v1/comment_like/delete/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfUFVCTElTSCJdLCJzdWIiOiJmYWxzZSIsImlhdCI6MTc2MzU0MjEzOCwiZXhwIjoxNzYzNjI4NTM4fQ.PjapKJz8QeTZpezWDasyodtd8HIR2vNiYXVVjZ65dSQKkX3wZthFpUs1JuJ9EV7SVhIHyA6rfrOj72xboMkmQw