### create Commit
POST localhost:8080/api/v1/comment/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzU1MDYxNiwiZXhwIjoxNzYzNjM3MDE2fQ.F9MeHag5zX051U5j5mAqmXOe2sH2NudVMl17TznhjowA82Lf8hZSTE7DqRbEfPBBiA6QAHWgMwoip_OuPMmDhw

{
  "content": "aaaa3",
  "articleId": "93a46013-8e44-4fd6-bade-7027269842df"
}

### update commit
PUT localhost:8080/api/v1/comment/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzU1MDYxNiwiZXhwIjoxNzYzNjM3MDE2fQ.F9MeHag5zX051U5j5mAqmXOe2sH2NudVMl17TznhjowA82Lf8hZSTE7DqRbEfPBBiA6QAHWgMwoip_OuPMmDhw

{
  "content": "aaaa1",
  "articleId": "93a46013-8e44-4fd6-bade-7027269842df"
}

### delate commit
DELETE localhost:8080/api/v1/comment/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzU1MDYxNiwiZXhwIjoxNzYzNjM3MDE2fQ.F9MeHag5zX051U5j5mAqmXOe2sH2NudVMl17TznhjowA82Lf8hZSTE7DqRbEfPBBiA6QAHWgMwoip_OuPMmDhw

### get Article Id and own
GET localhost:8080/api/v1/comment/article_own/93a46013-8e44-4fd6-bade-7027269842df
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzU1MDYxNiwiZXhwIjoxNzYzNjM3MDE2fQ.F9MeHag5zX051U5j5mAqmXOe2sH2NudVMl17TznhjowA82Lf8hZSTE7DqRbEfPBBiA6QAHWgMwoip_OuPMmDhw

### get By article ID
GET localhost:8080/api/v1/comment/article/93a46013-8e44-4fd6-bade-7027269842df
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjM3MTUwODMsImV4cCI6MTc2MzgwMTQ4M30.b0lLqSJMHbKji2HO_hCnU2FhnnL_DcOFiPCE9zSYjHcvCCxTHWbGtyqAoO1ybTTY9Yv0uX08Lsb9cZrO4yA7DA

### filter
POST localhost:8080/api/v1/comment/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjM3MTUwODMsImV4cCI6MTc2MzgwMTQ4M30.b0lLqSJMHbKji2HO_hCnU2FhnnL_DcOFiPCE9zSYjHcvCCxTHWbGtyqAoO1ybTTY9Yv0uX08Lsb9cZrO4yA7DA

{
  "articleId": "93a46013-8e44-4fd6-bade-7027269842df",
  "createdDateFrom": "2025-11-15"
}

### pagination
GET localhost:8080/api/v1/comment/pagination
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjM3MTUwODMsImV4cCI6MTc2MzgwMTQ4M30.b0lLqSJMHbKji2HO_hCnU2FhnnL_DcOFiPCE9zSYjHcvCCxTHWbGtyqAoO1ybTTY9Yv0uX08Lsb9cZrO4yA7DA