### create Commit
POST localhost:8080/api/v1/comment/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzM4MjMyMCwiZXhwIjoxNzYzNDY4NzIwfQ.zTO3sFA2bYoJJjDso-J1uHVZZUAWzEYSXPaoJ1F7N8oPIFieV9fz3Tb4mUvVV3atOr_t6p-Nbukl85SNQQAcHQ

{
  "content": "aaaa3",
  "articleId": "93a46013-8e44-4fd6-bade-7027269842df"
}

### update commit
PUT localhost:8080/api/v1/comment/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzM4MjMyMCwiZXhwIjoxNzYzNDY4NzIwfQ.zTO3sFA2bYoJJjDso-J1uHVZZUAWzEYSXPaoJ1F7N8oPIFieV9fz3Tb4mUvVV3atOr_t6p-Nbukl85SNQQAcHQ

{
  "content": "aaaa1",
  "articleId": "93a46013-8e44-4fd6-bade-7027269842df"
}

### delate commit
DELETE localhost:8080/api/v1/comment/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzM4MjMyMCwiZXhwIjoxNzYzNDY4NzIwfQ.zTO3sFA2bYoJJjDso-J1uHVZZUAWzEYSXPaoJ1F7N8oPIFieV9fz3Tb4mUvVV3atOr_t6p-Nbukl85SNQQAcHQ

### get commit
GET localhost:8080/api/v1/comment/get/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjMzODg2NDksImV4cCI6MTc2MzQ3NTA0OX0.il3nEPak2PXoUG5Pbo0L3SWm3Mq_t5eHcWHZMGN32a-tT4kpMgQPgQDN-UGh7AokQs0AzFSMlzB_dAaw9OcsWA

### get By article ID
GET localhost:8080/api/v1/comment/article/93a46013-8e44-4fd6-bade-7027269842df
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjMzODg2NDksImV4cCI6MTc2MzQ3NTA0OX0.il3nEPak2PXoUG5Pbo0L3SWm3Mq_t5eHcWHZMGN32a-tT4kpMgQPgQDN-UGh7AokQs0AzFSMlzB_dAaw9OcsWA

### filter
POST localhost:8080/api/v1/comment/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjMzODg2NDksImV4cCI6MTc2MzQ3NTA0OX0.il3nEPak2PXoUG5Pbo0L3SWm3Mq_t5eHcWHZMGN32a-tT4kpMgQPgQDN-UGh7AokQs0AzFSMlzB_dAaw9OcsWA

{
  "articleId": "93a46013-8e44-4fd6-bade-7027269842df",
  "createdDateFrom": "2025-11-15"
}