### create Commit
POST localhost:8080/api/v1/comment/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfUFVCTElTSCJdLCJzdWIiOiJmYWxzZSIsImlhdCI6MTc2NDE0ODI5NywiZXhwIjoxNzY0MjM0Njk3fQ.WJObYg7c7tpEtmu_Kw1gB7iMgZ0gMGPFY6r1VnqbQekS2eahbR_lPvUZ7zWYz20Pm1N5J_CaSpLMfDg8L6qf7Q

{
  "content": "aaaa2",
  "articleId": "93a46013-8e44-4fd6-bade-7027269842df"
}

### update commit
PUT localhost:8080/api/v1/comment/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzU1MDYxNiwiZXhwIjoxNzYzNjM3MDE2fQ.F9MeHag5zX051U5j5mAqmXOe2sH2NudVMl17TznhjowA82Lf8hZSTE7DqRbEfPBBiA6QAHWgMwoip_OuPMmDhw

{
  "content": "aaaa1",
  "articleId": "93a46013-8e44-4fd6-bade-7027269842df"
}

### delate commit
DELETE localhost:8080/api/v1/comment/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzU1MDYxNiwiZXhwIjoxNzYzNjM3MDE2fQ.F9MeHag5zX051U5j5mAqmXOe2sH2NudVMl17TznhjowA82Lf8hZSTE7DqRbEfPBBiA6QAHWgMwoip_OuPMmDhw

### get Article Id and own
GET localhost:8080/api/v1/comment/article_own/93a46013-8e44-4fd6-bade-7027269842df
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfTU9ERVJBVE9SIl0sInN1YiI6ImFkaGFtam9ueWF4c2hpYm92QGdtYWlsLmNvbSIsImlhdCI6MTc2MzU1MDYxNiwiZXhwIjoxNzYzNjM3MDE2fQ.F9MeHag5zX051U5j5mAqmXOe2sH2NudVMl17TznhjowA82Lf8hZSTE7DqRbEfPBBiA6QAHWgMwoip_OuPMmDhw

### get By article ID
GET localhost:8080/api/v1/comment/article/93a46013-8e44-4fd6-bade-7027269842df
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjQxNjYyNDgsImV4cCI6MTc2NDI1MjY0OH0.11Jq4dpjmEYAoBt7mZiP1IoKyWvM6GC-w0W9fBmELC3k3ZPMbIJj7c46HkBP6XRZ4ukMeiD7EzwCYX2JeG4oug

### filter
POST localhost:8080/api/v1/comment/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjQxNjYyNDgsImV4cCI6MTc2NDI1MjY0OH0.11Jq4dpjmEYAoBt7mZiP1IoKyWvM6GC-w0W9fBmELC3k3ZPMbIJj7c46HkBP6XRZ4ukMeiD7EzwCYX2JeG4oug

{
  "articleId": "93a46013-8e44-4fd6-bade-7027269842df",
  "createdDateFrom": "2025-11-15"
}

### pagination
GET localhost:8080/api/v1/comment/pagination
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjQxNjYyNDgsImV4cCI6MTc2NDI1MjY0OH0.11Jq4dpjmEYAoBt7mZiP1IoKyWvM6GC-w0W9fBmELC3k3ZPMbIJj7c46HkBP6XRZ4ukMeiD7EzwCYX2JeG4oug