### Create
POST localhost:8080/api/v1/profile
Content-Type: application/json
Authorization: Basic YWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb206MTIzNDU=

{
  "name": "Eshmat3",
  "surname": "Eshmatov3",
  "username": "eshmat3@gmail.com",
  "password": "12345",
  "roleList": [
    "ROLE_USER"
  ]
}

### update Admin
PUT localhost:8080/api/v1/profile/admin/1
Content-Type: application/json
Authorization: Basic YWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb206MTIzNDU=

{
  "roleList": [
    "ROLE_MODERATOR",
    "ROLE_PUBLISH"
  ],
  "status": "ACTIVE"
}

### update Own
PUT localhost:8080/api/v1/profile/own/39
Content-Type: application/json
Authorization: Basic YWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb206MTIzNDU=

{
  "name": "Adhamjon",
  "surname": "Yaxshiboyev",
  "username": "adhamjonyaxshiboyev@gmail.com"
}

### delete
DELETE localhost:8080/api/v1/profile/1
Content-Type: application/json
Authorization: Basic YWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb206MTIzNDU=

### Get all Pagination
GET localhost:8080/api/v1/profile/pagination?size=10
Content-Type: application/json
Authorization: Basic YWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb206MTIzNDU=

### Filter
POST localhost:8080/api/v1/profile/filter?size=10
Content-Type: application/json
Authorization: Basic YWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb206MTIzNDU=

{
  "createdDateFrom": "2025-10-20",
  "createdDateTo": "2025-10-25",
  "role": "ROLE_MODERATOR"
}

### Update password
PUT localhost:8080/api/v1/profile/password/1
Content-Type: application/json
Authorization: Basic YWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb206MTIzNDU=

{
  "currentPassword": "12345",
  "newPassword": "11111"
}

### Get By Id
GET localhost:8080/api/v1/profile/get/39
Content-Type: application/json
Authorization: Basic YWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb206MTIzNDU=