### Create
POST localhost:8080/api/v1/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJhZGhhbWpvbnlheHNoaWJveWV2QGdtYWlsLmNvbSIsImlhdCI6MTc2MTkyNzI4NSwiZXhwIjoxNzYyMDEzNjg1fQ.zCkv12sbabzcBk0e6DZHMImxbIx3QUZVq1CCZpXINb8gF5OyyB4fDgzFNnwpYDbDzrh5FFXu1jVaH-eMEVykww

{
  "name": "Eshmat3",
  "surname": "Eshmatov3",
  "username": "eshmat3@gmail.com",
  "password": "12345",
  "roleList": [
    "ROLE_USER"
  ]
}

### update Admin
PUT localhost:8080/api/v1/profile/admin/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJhZGhhbWpvbnlheHNoaWJveWV2QGdtYWlsLmNvbSIsImlhdCI6MTc2MTkyNzI4NSwiZXhwIjoxNzYyMDEzNjg1fQ.zCkv12sbabzcBk0e6DZHMImxbIx3QUZVq1CCZpXINb8gF5OyyB4fDgzFNnwpYDbDzrh5FFXu1jVaH-eMEVykww

{
  "roleList": [
    "ROLE_MODERATOR",
    "ROLE_PUBLISH"
  ],
  "status": "ACTIVE"
}

### update Own
PUT localhost:8080/api/v1/profile/own/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJhZGhhbWpvbnlheHNoaWJveWV2QGdtYWlsLmNvbSIsImlhdCI6MTc2MTkyNzI4NSwiZXhwIjoxNzYyMDEzNjg1fQ.zCkv12sbabzcBk0e6DZHMImxbIx3QUZVq1CCZpXINb8gF5OyyB4fDgzFNnwpYDbDzrh5FFXu1jVaH-eMEVykww

{
  "name": "Eshmat30",
  "surname": "Eshmatov30",
  "username": "eshmat3@gmail.com",
  "password": "12345"
}

### delete
DELETE localhost:8080/api/v1/profile/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJhZGhhbWpvbnlheHNoaWJveWV2QGdtYWlsLmNvbSIsImlhdCI6MTc2MTkyNzI4NSwiZXhwIjoxNzYyMDEzNjg1fQ.zCkv12sbabzcBk0e6DZHMImxbIx3QUZVq1CCZpXINb8gF5OyyB4fDgzFNnwpYDbDzrh5FFXu1jVaH-eMEVykww

### Get all Pagination
GET localhost:8080/api/v1/profile/pagination?size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJhZGhhbWpvbnlheHNoaWJveWV2QGdtYWlsLmNvbSIsImlhdCI6MTc2MTkyNzI4NSwiZXhwIjoxNzYyMDEzNjg1fQ.zCkv12sbabzcBk0e6DZHMImxbIx3QUZVq1CCZpXINb8gF5OyyB4fDgzFNnwpYDbDzrh5FFXu1jVaH-eMEVykww

### Filter
POST localhost:8080/api/v1/profile/filter?size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJhZGhhbWpvbnlheHNoaWJveWV2QGdtYWlsLmNvbSIsImlhdCI6MTc2MTkyNzI4NSwiZXhwIjoxNzYyMDEzNjg1fQ.zCkv12sbabzcBk0e6DZHMImxbIx3QUZVq1CCZpXINb8gF5OyyB4fDgzFNnwpYDbDzrh5FFXu1jVaH-eMEVykww

{
  "createdDateFrom": "2025-10-20",
  "createdDateTo": "2025-10-25",
  "role": "ROLE_MODERATOR"
}

### Update password
PUT localhost:8080/api/v1/profile/password/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJhZGhhbWpvbnlheHNoaWJveWV2QGdtYWlsLmNvbSIsImlhdCI6MTc2MTkyNzI4NSwiZXhwIjoxNzYyMDEzNjg1fQ.zCkv12sbabzcBk0e6DZHMImxbIx3QUZVq1CCZpXINb8gF5OyyB4fDgzFNnwpYDbDzrh5FFXu1jVaH-eMEVykww

{
  "currentPassword": "12345",
  "newPassword": "11111"
}

### Get By Id
GET localhost:8080/api/v1/profile/get/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJhZGhhbWpvbnlheHNoaWJveWV2QGdtYWlsLmNvbSIsImlhdCI6MTc2MTkyNzI4NSwiZXhwIjoxNzYyMDEzNjg1fQ.zCkv12sbabzcBk0e6DZHMImxbIx3QUZVq1CCZpXINb8gF5OyyB4fDgzFNnwpYDbDzrh5FFXu1jVaH-eMEVykww