### Create region
POST localhost:8080/api/v1/region
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjI0OTU3MzksImV4cCI6MTc2MjU4MjEzOX0.FnA6Fr22MRPc4Hx6Ej2ZdjNy3HEyeZJ0vD5rKsnOtByxhEszSQcBiuvaPWHI5D4CyD60cLJOPal06CKnxGYwww

{
  "orderNumber": 2,
  "nameUz": "Toshkent 2",
  "nameRu": "Ташкент 2",
  "nameEn": "Tashkent 2",
  "regionKey": "tashkent2"
}

### Get all region
GET localhost:8080/api/v1/region
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjI0OTU3MzksImV4cCI6MTc2MjU4MjEzOX0.FnA6Fr22MRPc4Hx6Ej2ZdjNy3HEyeZJ0vD5rKsnOtByxhEszSQcBiuvaPWHI5D4CyD60cLJOPal06CKnxGYwww

### Update region
PUT localhost:8080/api/v1/region/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjI0OTU3MzksImV4cCI6MTc2MjU4MjEzOX0.FnA6Fr22MRPc4Hx6Ej2ZdjNy3HEyeZJ0vD5rKsnOtByxhEszSQcBiuvaPWHI5D4CyD60cLJOPal06CKnxGYwww

{
  "orderNumber": 1,
  "nameUz": "T 1",
  "nameRu": "Ташкент 1",
  "nameEn": "Tashkent 1",
  "regionKey": "tashkent1"
}

### Delete region
DELETE localhost:8080/api/v1/region/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjI0OTU3MzksImV4cCI6MTc2MjU4MjEzOX0.FnA6Fr22MRPc4Hx6Ej2ZdjNy3HEyeZJ0vD5rKsnOtByxhEszSQcBiuvaPWHI5D4CyD60cLJOPal06CKnxGYwww

### Get by lang
GET localhost:8080/api/v1/region/lang
Accept-Language: EN