### Create region
POST localhost:8080/api/v1/region
Content-Type: application/json
Authorization: Basic YWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb206MTIzNDU=

{
  "orderNumber": 2,
  "nameUz": "Toshkent 2",
  "nameRu": "Ташкент 2",
  "nameEn": "Tashkent 2",
  "regionKey": "tashkent2"
}

### Get all region
GET localhost:8080/api/v1/region
Content-Type: application/json
Authorization: Basic YWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb206MTIzNDU=

### Update region
PUT localhost:8080/api/v1/region/1
Content-Type: application/json
Authorization: Basic YWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb206MTIzNDU=

{
  "orderNumber": 1,
  "nameUz": "T 1",
  "nameRu": "Ташкент 1",
  "nameEn": "Tashkent 1",
  "regionKey": "tashkent1"
}

### Delete region
DELETE localhost:8080/api/v1/region/
Content-Type: application/json
Authorization: Basic YWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb206MTIzNDU=

### Get by lang
GET localhost:8080/api/v1/region/lang
Accept-Language: EN