### saved Article
POST localhost:8080/api/v1/saved_article/93a46013-8e44-4fd6-bade-7027269842df
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjM4ODI1NjIsImV4cCI6MTc2Mzk2ODk2Mn0.tfeBqRIvVcTe2-GP6WQGz6y_g_5vdr_Ak6GaV-Da09JJcToibS66wwLFllJ29VQzBsd-EBfGx48b_jGavX6o8A

### Delete Article
DELETE localhost:8080/api/v1/saved_article/93a46013-8e44-4fd6-bade-7027269842df
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjM4ODI1NjIsImV4cCI6MTc2Mzk2ODk2Mn0.tfeBqRIvVcTe2-GP6WQGz6y_g_5vdr_Ak6GaV-Da09JJcToibS66wwLFllJ29VQzBsd-EBfGx48b_jGavX6o8A

### get saved article
GET localhost:8080/api/v1/saved_article/get
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwic3ViIjoiYWRoYW1qb255YXhzaGlib3lldkBnbWFpbC5jb20iLCJpYXQiOjE3NjM4ODI1NjIsImV4cCI6MTc2Mzk2ODk2Mn0.tfeBqRIvVcTe2-GP6WQGz6y_g_5vdr_Ak6GaV-Da09JJcToibS66wwLFllJ29VQzBsd-EBfGx48b_jGavX6o8A
