### get by phone
GET localhost:8080/api/v1/sms/phone?phone=998904917705

### get by date
GET localhost:8080/api/v1/sms/date?date="2025-10-27"

### get pagination
GET localhost:8080/api/v1/sms/pagination
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJhZGhhbWpvbnlheHNoaWJveWV2QGdtYWlsLmNvbSIsImlhdCI6MTc2MTkyNzI4NSwiZXhwIjoxNzYyMDEzNjg1fQ.zCkv12sbabzcBk0e6DZHMImxbIx3QUZVq1CCZpXINb8gF5OyyB4fDgzFNnwpYDbDzrh5FFXu1jVaH-eMEVykww